meta_product_name: "Bet On It"
meta_title: "Bet On It - Risk Nothing... Win Daily"
meta_description: "The worlds first free betting pool. Choose the winners from all you favorite sports to win money every night while risking nothing!"
meta_image: "sports-page.png"
# twitter_account: "@product_twitter_account"
